export const ADMIN_TOP_MOST_REVIEWED_SUCCESS = 'ADMIN_TOP_MOST_REVIEWED_SUCCESS';
export const ADMIN_TOP_MOST_REVIEWED_FAIL = 'ADMIN_TOP_MOST_REVIEWED_FAIL';

export const ADMIN_TOP_MOST_RATING_SUCCESS = 'ADMIN_TOP_MOST_RATING_SUCCESS ';
export const ADMIN_TOP_MOST_RATING_FAIL = 'ADMIN_TOP_MOST_RATING_FAIL';

export const ADMIN_TOP_MOST_JOBSEEKER_SUCCESS = 'ADMIN_TOP_MOST_JOBSEEKER_SUCCESS';
export const ADMIN_TOP_MOST_JOBSEEKER_FAIL = 'ADMIN_TOP_MOST_JOBSEEKER_FAIL';

export const ADMIN_GET_ALL_REVIEWS_SUCCESS = 'ADMIN_GET_ALL_REVIEWS_SUCCESS';
export const ADMIN_GET_ALL_REVIEWS_FAIL= 'ADMIN_GET_ALL_REVIEWS_FAIL';


export const ADMIN_TOP_MOST_CEOS_SUCCESS = 'ADMIN_TOP_MOST_CEOS_SUCCESS';
export const ADMIN_TOP_MOST_CEOS_FAIL = 'ADMIN_TOP_MOST_CEOS_FAIL';


export const ADMIN_LIST_ALL_COMPANIES_SUCCESS = 'ADMIN_LIST_ALL_COMPANIES_SUCCESS';
export const ADMIN_LIST_ALL_COMPANIES_FAIL = 'ADMIN_LIST_ALL_COMPANIES_FAIL';

export const ADMIN_UPDATE_PHOTO_STATUS_SUCCESS = 'ADMIN_UPDATE_PHOTO_STATUS_SUCCESS';
export const ADMIN_UPDATE_PHOTO_STATUS_FAIL = 'ADMIN_UPDATE_PHOTO_STATUS_FAIL';


export const ADMIN_UPDATE_VIEW_COUNT_SUCCESS = 'ADMIN_UPDATE_VIEW_COUNT_SUCCESS';
export const ADMIN_UPDATE_VIEW_COUNT_FAIL = 'ADMIN_UPDATE_VIEW_COUNT_FAIL';


export const ADMIN_GET_TOP_VIEW_COUNT_SUCCESS = 'ADMIN_GET_TOP_VIEW_COUNT_SUCCESS';
export const ADMIN_GET_TOP_VIEW_COUNT_FAIL = 'ADMIN_GET_TOP_VIEW_COUNT_FAIL';