
export const COMPANY_LIST_SUCCESS = 'COMPANY_LIST_SUCCESS';
export const COMPANY_LIST_FAIL = 'COMPANY_LIST_FAIL';

export const COMPANY_LIST_REVIEWS_SUCCESS = 'COMPANY_LIST_REVIEWS_SUCCESS';
export const COMPANY_LIST_REVIEWS_FAIL = 'COMPANY_LIST_REVIEWS_FAIL';


export const UPDATE_REVIEW_STATUS_SUCCESS = 'UPDATE_REVIEW_STATUS_SUCCESS';
export const UPDATE_REVIEW_STATUS_FAIL = 'UPDATE_REVIEW_STATUS_FAIL';

export const UPDATE_HELPFUL_COUNT_SUCCESS = 'UPDATE_HELPFUL_COUNT_SUCCESS';
export const UPDATE_HELPFUL_COUNT_FAIL = 'UPDATE_HELPFUL_COUNT_FAIL';

export const COMPANY_LIST_FEATURE_REVIEWS_SUCCESS = 'COMPANY_LIST_FEATURE_REVIEWS_SUCCESS';
export const COMPANY_LIST_FEATURE_REVIEWS_FAIL = 'COMPANY_LIST_FEATURE_REVIEWS_FAIL';