

export const GET_JOB_APPLICANTS_REQUEST = 'GET_JOB_APPLICANTS_REQUEST'
export const GET_JOB_APPLICANTS_SUCCESS = 'GET_JOB_APPLICANTS_SUCCESS'
export const GET_JOB_APPLICANTS_FAIL = 'GET_JOB_APPLICANTS_FAIL'
export const GET_JOB_APPLICANTS_RESET = 'GET_JOB_APPLICANTS_RESET'

export const UPDATE_APPLICATION_STATUS_REQUEST = 'UPDATE_APPLICATION_STATUS_REQUEST'
export const UPDATE_APPLICATION_STATUS_SUCCESS = 'UPDATE_APPLICATION_STATUS_SUCCESS'
export const UPDATE_APPLICATION_STATUS_FAIL = 'UPDATE_APPLICATION_STATUS_FAIL'
