export const GET_EMPLOYER_MESSAGES_REQUEST = 'GET_EMPLOYER_MESSAGES_REQUEST';
export const GET_EMPLOYER_MESSAGES_SUCCESS = 'GET_EMPLOYER_MESSAGES_SUCCESS';
export const GET_EMPLOYER_MESSAGES_FAIL = 'GET_EMPLOYER_MESSAGES_FAIL';

export const GET_USER_MESSAGES_REQUEST = 'GET_USER_MESSAGES_REQUEST';
export const GET_USER_MESSAGES_SUCCESS = 'GET_USER_MESSAGES_SUCCESS';
export const GET_USER_MESSAGES_FAIL = 'GET_USER_MESSAGES_FAIL';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';
export const SEND_MESSAGE_RESET = 'SEND_MESSAGE_RESET';

export const REPLY_MESSAGE_SUCCESS = 'REPLY_MESSAGE_SUCCESS';

export const GET_DISTINCT_EMPLOYERS = 'GET_DISTINCT_EMPLOYERS';
export const GET_MSGS_JOBSEEKERS = 'GET_MSGS_JOBSEEKERS';
export const MESSAGE_ERROR = 'MESSAGE_ERROR';